apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mvm-vigo #cluster name
  region: ap-southeast-1 #desired region
  version: "1.16"

nodeGroups:
  - name: ng-1 #cluster node group name
    instanceType: t2.xlarge #desired instance type
    desiredCapacity: 3 #desired nodes count / capacity
    ssh:
      allow: false # if true - will use ~/.ssh/id_rsa.pub as the default ssh key
      #publicKeyPath: ~/.ssh/ec2_id_rsa.pub #you can specify the public key path likr this as well


vpc:
    id: vpc-faffd79d
#   subnets:
#     public:
#       ap-south-1a: { id: subnet-0a107d90ebd39ce54 }
#       ap-south-1c: { id: subnet-0ad4b277d7a907339 }
#       ap-south-1b: { id: subnet-0ecd01e7174b725b5 }