apiVersion: v1
kind: Service
metadata:
  name: admin-api
  labels:
    app: admin-api
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
      protocol: TCP
      name: http
  selector:
    app: admin-api